// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSessions(ctx context.Context, arg CreateSessionsParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUserBypublic_address(ctx context.Context, publicAddress string) (User, error)
	UpdateLastLogin(ctx context.Context, id int32) (User, error)
	UpdateUserNonce(ctx context.Context, arg UpdateUserNonceParams) (User, error)
	UserExists(ctx context.Context, publicAddress string) (bool, error)
}

var _ Querier = (*Queries)(nil)
